# _config.yml
title: limosa.work
description: Passive, truthful time & location for outdoor crews
url: https://limosa.work
baseurl: ""

theme: jekyll-theme-slate
show_downloads: false

sass:
  sass_dir: assets/css
  style: compressed

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

defaults:
  - scope: { path: "", type: "pages" }
    values: { layout: default }
  - scope: { path: "docs", type: "pages" }
    values: { layout: default }

lang: en

exclude:
  - README.md
  - mkdocs.yml
  - .github
  - node_modules
  - vendor

