# =========================
# limosa.work — Jekyll config
# =========================

# ---- Site identity
title: limosa.work
description: Passive, truthful time & location for outdoor crews
url: https://limosa.work      # custom domain
baseurl: ""                   # keep empty when using a custom domain

# ---- Theme
theme: minima
minima:
  skin: classic               # 'classic', 'dark', 'auto', etc.
# Header logo (ensure this file exists)
logo: /assets/img/logo.png

# ---- Build & Markdown
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
permalink: pretty             # /path/ instead of /path.html

# ---- Plugins (all supported by GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# ---- Header navigation (uses each page's front-matter title)
header_pages:
  - index.md
  - docs/01-methodology.md
  - docs/02-product.md
  - docs/03-architecture.md
  - docs/04-casestories.md
  - docs/05-workshops.md
  - docs/06-brand.md

# ---- Defaults (consistent layout)
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: page
  - scope:
      path: "docs"
      type: "pages"
    values:
      layout: page

# ---- SEO / Social (optional)
lang: en
# github_username: limosa-work
# twitter_username: yourhandle

# ---- Exclusions (do not publish)
exclude:
  - README.md
  - mkdocs.yml
  - .github
  - node_modules
  - vendor

