site_name: limosa.work
site_url: https://limosa.work
repo_url: https://github.com/<YOUR_USERNAME>/limosa.work
theme:
  name: material
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - content.code.copy
    - search.highlight
    - search.share
markdown_extensions:
  - admonition
  - toc:
      permalink: true
  - tables
  - attr_list

nav:
  - Home: index.md
  - Methodology: docs/01-methodology.md
  - Product: docs/02-product.md
  - Architecture: docs/03-architecture.md
  - Case Stories: docs/04-casestories.md
  - Workshops: docs/05-workshops.md
  - Brand: docs/06-brand.md

extra:
  social:
    - icon: material/bird
      link: https://limosa.work
